### ISSUE TITLE
startConversation not waiting for response

### ISSUE THREAD

**Issue by dale-french** [howdyai/botkit-starter-facebook#10]
Hey guys

I'm using the basic convo example included in the starter repo
```
controller.hears(['color'], 'message_received', function (bot, message) {

        bot.startConversation(message, function (err, convo) {
            convo.say('This is an example of using convo.ask with a single callback.');

            convo.ask('What is your favorite color?', function (response, convo) {

                convo.say('Cool, I like ' + response.text + ' too!');
                convo.next();

            });
        });

    });
```

My bot does not wait for a response and just goes straight to 'Cool, I like (blank) too!'

I am using a Huawei p9 lite and hosting on Heroku.

Any ideas?

Thanks

**Comment by peterswimm** [comment]
You should post general Botkit questions over on the main repo:
https://github.com/howdyai/botkit/issues

or try asking on our Public Slack in the #botkit channel:
https://community.botkit.ai/
