### ISSUE TITLE
npm install is failing

### ISSUE THREAD

**Issue by aidonsnous** [howdyai/botkit-starter-facebook#4]
I first cloned the repository everything worked fine but when I typed the command 

> `npm install`

 to install dependencies, including Botkit it failed giving me this message:
![image npm failing](https://cloud.githubusercontent.com/assets/13017395/23866352/9db9fb42-0829-11e7-8f1c-768c3d82fa31.PNG)

**Comment by peterswimm** [comment]
Have you tried reinstalling NPM? It seems like GIT is not installed on your system.

**Comment by aidonsnous** [comment]
GIT is installed, I cloned howdyai/bokit-starter-facebook repository  and I've added git to the path environment variable

**Comment by peterswimm** [comment]
Can you post that log in your screenshot anywhere for people to view?

**Comment by aidonsnous** [comment]
I don't get what you are saying, which "log"?  where do you mean by "anywhere"?
Here down is the screenshot of the system environment path variable:
![Uploading CaptureSystemVariable.PNG…]()

**Comment by peterswimm** [comment]
I was referring to that npm-debug.log mentioned in the initial screenshot.

**Comment by aidonsnous** [comment]
I don't know which part can meet the need, I chose to upload the file itself.

[npm-debug.txt](https://github.com/howdyai/botkit-starter-facebook/files/842332/npm-debug.txt)

**Comment by peterswimm** [comment]
It looks like either git is not installed or the path is wrong. I cant see your screenshot, but perhaps try installing the git windows installer again, and then reinstall NPM?

I found discussion of this over here:
http://stackoverflow.com/questions/19290899/git-is-not-installed-or-not-in-the-path

**Comment by aidonsnous** [comment]
The problem which made the path I added to not work was the git application was not in the main folder C:\Program Files\Git but in C:\Program Files\Git\cmd . Thanks for the support.
