### ISSUE TITLE
Git repo is empty

### ISSUE THREAD

**Issue by dale-french** [howdyai/botkit-starter-facebook#9]
I created the bot in botkit studio and deployed to Heroku from there. 
If I clone the Heroku repo I get told 'warning: You appear to have cloned an empty repository.'
Any ideas?

**Comment by peterswimm** [comment]
This is not exactly a Botkit specific issue, take a look here:

https://help.heroku.com/XOBUHLKQ/why-do-i-see-a-message-you-appear-to-have-cloned-an-empty-repository-when-using-heroku-git-clone
